Controllers/InterventionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Net.Http;
using Newtonsoft.Json;
using RocketElevatorsCustomerPortal.Models;
using System.Dynamic;
using Microsoft.AspNetCore.Authorization;

// reference https://www.yogihosting.com/aspnet-core-consume-api/

namespace RocketElevatorsCustomerPortal.Controllers
{
    [Authorize]
    public class InterventionController : Controller
    {
        // [HttpPost]
        // public ActionResult AddIntervention(IEnumerable<Intervention> interfaces)
        // {
        //     return View();
        // }
        public async Task<IActionResult> IndexAsync()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.Buildings = await GetBuildings();
            mymodel.Batteries = await GetBatteries();
            mymodel.Columns = await GetColumns();
            mymodel.Elevators = await GetElevators();
            // mymodel.Customer = FetchCustomer(string email);
            return View(mymodel);
        }

        // CUSTOMERS
        //public async Task<IActionResult> Index()
        //{
        //    List<Customer> customerList = new List<Customer>();
        //    using (var httpClient = new HttpClient())
        //    {
        //        //HTTP GET request to the API
        //        using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/interventions/pending"))
        //        {
        //            //data returned by the API is fetched from the code
        //            string apiResponse = await response.Content.ReadAsStringAsync();
        //            //Deserialize the JSON to a List type object
        //            customerList = JsonConvert.DeserializeObject<List<Customer>>(apiResponse);
        //        }
        //    }
        //    return View(customerList);
        //}

        // BUILDINGS
        public async Task<IEnumerable<Building>> GetBuildings()
        {
            List<Building> buildingList = new List<Building>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/building"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    buildingList = JsonConvert.DeserializeObject<List<Building>>(apiResponse);
                }
            }
            return buildingList;
        }
        // BATTERIES
        public async Task<IEnumerable<Battery>> GetBatteries()
        {
            List<Battery> batteryList = new List<Battery>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/batteries"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    batteryList = JsonConvert.DeserializeObject<List<Battery>>(apiResponse);
                }
            }
            return batteryList;
        }
        // COLUMNS
        public async Task<IEnumerable<Column>> GetColumns()
        {
            List<Column> columnList = new List<Column>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/columns"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    columnList = JsonConvert.DeserializeObject<List<Column>>(apiResponse);
                }
            }
            return columnList;
        }
        // ELEVATORS
        public async Task<IEnumerable<Elevator>> GetElevators()
        {
            List<Elevator> elevatorList = new List<Elevator>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/elevators"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    elevatorList = JsonConvert.DeserializeObject<List<Elevator>>(apiResponse);
                }
            }
            return elevatorList;
        }
        
        //CUSTOMER LOGGED IN
        // public async Task<IEnumerable<Customer>> FetchCustomer(string email)
        public Customer FetchCustomer([FromRoute] string email)
        {
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                var result = httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/customer/" + email)
                    .Result;
               //data returned by the API is fetched from the code
                    string apiResult = result.Content.ReadAsStringAsync().Result;
                    //Deserialize the JSON to a List type object
                    Customer customer = JsonConvert.DeserializeObject<Customer>(apiResult);
                    return customer;
            }
        }

    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Net.Http;
using Newtonsoft.Json;
using RocketElevatorsCustomerPortal.Models;
using System.Dynamic;
using System.Net.Http.Headers;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace RocketElevatorsCustomerPortal.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        public async Task<IActionResult> IndexAsync()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.Batteries = await GetBatteries();
            mymodel.Columns = await GetColumns();
            mymodel.Elevators = await GetElevators();
            mymodel.Customer = await GetAccount();
            mymodel.Address = await GetAddress();
            mymodel.Building = await GetBuildings();
            return View(mymodel);
        }
        
        // Customers
        public async Task<IEnumerable<Customer>> GetAccount()
        {
            List<Customer> customerList = new List<Customer>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/customer"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    customerList = JsonConvert.DeserializeObject<List<Customer>>(apiResponse);
                }
            }
            return customerList;
        }

        // Address
        public async Task<IEnumerable<Address>> GetAddress()
        {
            List<Address> addressList = new List<Address>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/address"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    addressList = JsonConvert.DeserializeObject<List<Address>>(apiResponse);
                }
            }
            return addressList;
        }
        
        // BUILDINGS
        public async Task<IEnumerable<Building>> GetBuildings()
        {
            List<Building> buildingList = new List<Building>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/building"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    buildingList = JsonConvert.DeserializeObject<List<Building>>(apiResponse);
                }
            }
            return buildingList;
        }

        // BATTERIES
        public async Task<IEnumerable<Battery>> GetBatteries()
        {
            List<Battery> batteryList = new List<Battery>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/batteries"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    batteryList = JsonConvert.DeserializeObject<List<Battery>>(apiResponse);
                }
            }
            return batteryList;
        }

        // COLUMNS
        public async Task<IEnumerable<Column>> GetColumns()
        {
            List<Column> columnList = new List<Column>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/columns"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    columnList = JsonConvert.DeserializeObject<List<Column>>(apiResponse);
                }
            }
            return columnList;
        }

        // ELEVATORS
        public async Task<IEnumerable<Elevator>> GetElevators()
        {
            List<Elevator> elevatorList = new List<Elevator>();
            using (var httpClient = new HttpClient())
            {
                //HTTP GET request to the API
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/elevators"))
                {
                    //data returned by the API is fetched from the code
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //Deserialize the JSON to a List type object
                    elevatorList = JsonConvert.DeserializeObject<List<Elevator>>(apiResponse);
                }
            }
            return elevatorList;
        }

        //Update Contact Info
         // public async Task<Customer> ModifyContactInfo(int id)
         public async Task<IActionResult> ModifyContactInfo(int id)
        {
            Customer customer = new Customer();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/customer/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    customer = JsonConvert.DeserializeObject<Customer>(apiResponse);
                }
            }
            return View(customer);
        }
        
        // [HttpPost]
        // public async Task<Customer> ModifyContactInfo(Customer customer)
        // public async Task<IActionResult> ModifyContactInfo(Customer customer)
        // {
        //     Customer modifyCustomer = new Customer();
        //     using (var httpClient = new HttpClient())
        //     {
        //         var content = new MultipartFormDataContent();
        //         content.Add(new StringContent(customer.id.ToString()), "id");
        //         content.Add(new StringContent(customer.CompanyName), "CompanyName");
        //         content.Add(new StringContent(customer.NameOfContact), "NameOfContact");
        //         content.Add(new StringContent(customer.CompanyContactPhone), "CompanyContactPhone");
        //         content.Add(new StringContent(customer.EmailOfTheCompany), "EmailOfTheCompany");
        //         content.Add(new StringContent(customer.CompanyDescription), "CompanyDescription");
        //         content.Add(new StringContent(customer.NameOfServiceTechAuthority), "NameOfServiceTechAuthority");
        //         content.Add(new StringContent(customer.TechAuhtorityPhone), "TechAuhtorityPhone");
        //         content.Add(new StringContent(customer.TechManagerServiceEmail), "TechManagerServiceEmail");
        //
        //         using (var response = await httpClient.PutAsync("https://rocketapis.azurewebsites.net/api/customer", content))
        //         {
        //             string apiResponse = await response.Content.ReadAsStringAsync();
        //             ViewBag.Result = "Success";
        //             modifyCustomer = JsonConvert.DeserializeObject<Customer>(apiResponse);
        //         }
        //     }
        //     return View(modifyCustomer);
        // }

        // TESTING V2
        // public async Task<IActionResult> ModifyContactInfo(Customer customer)
        // {
        //     Customer modifyCustomer = new Customer();
        //     HttpClient client = new HttpClient();
        //     client.BaseAddress = new Uri("https://rocketapis.azurewebsites.net");
        //     client.DefaultRequestHeaders
        //         .Accept
        //         .Add(new MediaTypeWithQualityHeaderValue("application/json")); //ACCEPT header
        //
        //     HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, "api/customer");
        //     Console.WriteLine(request);
        //     request.Content = new StringContent("{\"companyName\",\"nameOfContact\"}",
        //         Encoding.UTF8,
        //         "application/json"); //CONTENT-TYPE header
        //
        //     client.SendAsync(request)
        //         .ContinueWith(responseTask => { Console.WriteLine("Response: {0}", responseTask.Result); });
        //     
        //     return View(modifyCustomer);
        // }

        //Update Address Info
          public async Task<IActionResult> ModifyAddressInfo(int id)
        {
            Address address = new Address();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://rocketapis.azurewebsites.net/api/address/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    address = JsonConvert.DeserializeObject<Address>(apiResponse);
                }
            }
            return View(address);
        }
          
        //
        // [HttpPost]

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rocket Elevators Customer Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" />
</head>
<body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" asp-controller="Home" asp-action="Index">Rocket Elevators</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            @*<a class="nav-link px-3" href="#">Sign out</a>*@

            <div class="nav-link px-3">
                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button id="logout" type="submit" class="nav-link btn btn-link text-light">Logout</button>
                </form>
            </div>

        </div>
    </div>
</header>

@*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Customer Portal</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@

<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">
                            <span data-feather="home"></span>
                            Portal Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Intervention" asp-action="Index">
                            <span data-feather="file"></span>
                            Intervention
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Product" asp-action="Index">
                            <span data-feather="layers"></span>
                            Products
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="users"></span>
                            Chat
                        </a>
                    </li>
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link" href="#"> *@
                    @*         <span data-feather="bar-chart-2"></span> *@
                    @*         Reports *@
                    @*     </a> *@
                    @* </li> *@
                    @*<li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Integrations
                        </a>
                    </li>*@
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Saved reports</span>
                    <a class="link-secondary" href="#" aria-label="Add a new report">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Current month
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Last quarter
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Social engagement
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Year-end
                        </a>
                    </li>
                </ul>
            </div>
        </nav>


@*<div class="container">*@
    @* <main role="main" class="pb-3"> *@
    @RenderBody()
    @* </main> *@
    @*</div>*@
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Rocket Elevators - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>